### PR TITLE
Add location attribute to sent patient registration

### PR DESCRIPTION
**Pull request by yousefhamza**
and fixing a bug of duplicated first address in
patient view controller.

Signed-off-by: Yousef Hamza <jo.adam.93@gmail.com>

### CODE REVIEW

**Comment by yousefhamza** [comment]
I have been waiting for translations for like a week now I will set a reminder now too, but I guess after that we have to make a release.

I think we should drop support for other languages until updated and add them in a later minor release, what do you think about that?

Thanks.

**Comment by Undo1** [comment]
@yousefhamza Is the problem just that the current translations are partial?

**Comment by yousefhamza** [comment]
Yes

**Comment by Undo1** [comment]
In that case, I'd suggest just releasing as-is. A partial localization is
better than no localization.

**Comment by yousefhamza** [comment]
Hey @Undo1, review those and make a release.

**Comment by Undo1** [comment]
Merged, but I can't review for a release right now. It'd be nice if @harshadura could go over the app and see if anything sticks out as needing fixed, I'm busy with school and such right now.

**Pull request merged**
