### PR TITLE
Active visits

### PR DESCRIPTION
**Pull request by yousefhamza**
Adding ability to check all active visits from within the app with lazy loading.

### CODE REVIEW

**Comment by yousefhamza** [comment]
@harshadura let me know what you think.

**Comment by Undo1** [comment]
Could you commit `OpenMRS-iOS.xcodeproj/project.pbxproj`? Thanks! :)

**Comment by yousefhamza** [comment]
Done

**Comment by Undo1** [comment]
I'm logging in on the demo server, and this works for two reloads, then freezes (exception breakpoint) on the third reload:
```
2015-06-07 19:39:38.842 OpenMRS-iOS[6806:2038725] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (161) must be equal to the number of rows contained in that section before the update (162), plus or minus the number of rows inserted or deleted from that section (1 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'
```

**Comment by yousefhamza** [comment]
This will fix it.

**Pull request merged**
