### PR TITLE
Dynamic typing and other stuff

### PR DESCRIPTION
**Pull request by yousefhamza**
- Add dynamic typing support
- Full state restoration
- New Visits cell design **check this one particularly and let me know what you think.
- 0 obs label in encounters details with no obs.

### CODE REVIEW

**Comment by yousefhamza** [comment]
French language added.

**Comment by harshadura** [comment]
This is awesome, Fantastic job @yousefhamza !

**Comment by Undo1** [comment]
I like the visit cells, one question:

fullsizerender

Are you sure we need the numbers on them? I'm not sure they really mean anything - @harshadura thoughts?

**Comment by yousefhamza** [comment]
Yes It's essential, more than the awesome looks it give (A), For a longer list of visits or in active visits for example it gives a sense where you are in this list. that was the motivation in the first place to make it but when it's added it looked great.

**Comment by Undo1** [comment]
Also, a couple things we can add to the localization (which is already very thorough, great work!):

 - [ ] The HUDs we show for logins (L40, 48, 52 of OpenMRSAPIManager.m)
 - [ ] On the active visits screen, the active/ended labels
 - [ ] "Close" in the navigation bar isn't localized, like when you view a patient

Otherwise, those are the only things I can find in English after I switch to French. A couple other notes: 

 - [ ] You're hitting the same problem I was when I tried to make the cells autoresize - see this screenshot:

fullsizerender 1

 - [ ] Instead of saying `"0 obs"`, you might try `No details`

Anyway, these are all small details. Thanks for all your hard work!

**Comment by yousefhamza** [comment]
Yea but I don't wanna release localisation file very -often- I listed the stuff you mentioned already to be added in the localisation file soon.

and about Identifiers I will be adding a custom cell for it too.

**Comment by Undo1** [comment]
Awesome, that sounds good.

**Comment by yousefhamza** [comment]
- Fixed syncing predicate
- Fixing saving to Coredata for Booleans
- Adding syncing of existing saved patients with online on launch to start at a good well know state AND most importantly not overload the server with very old updates at release of this version.
- Updating saved patients when loaded with internet connection and not edited
- Custom idetifier cell
- Add the translations you pointed out and added the german file -The base file is now the only one a head with the new ones and english-
- Some fixes here and there.

**Comment by Undo1** [comment]
Just tested this, it gets stuck at launch with the "make sure you are connected to the internet" thing. This is upgrading from an install of the application from a couple months ago - which is pretty close to the latest public version, on an iPhone 6. The error we get:

```
Printing description of error:
Error Domain=NSSQLiteErrorDomain Code=1 "The operation couldn’t be completed. (NSSQLiteErrorDomain error 1.)" UserInfo=0x17406e200 {EncryptedStoreErrorMessage=no such column: ecdPatient.upToDate}
```

So two things here:

 - [ ] There should probably be some way for the user to get past that screen if there isn't a connection
 - [ ] Looks like there's a migration error here or something, might want to look into that

Manually skipping the check shows that the new identifier cell looks great :)

**Comment by yousefhamza** [comment]
When line exactly cause that error?

**Comment by Undo1** [comment]
I did a little hunting for it, and I couldn't figure out exactly what causes it. From that error, though, it seems to be something to do with SQL. You might try going back to the last release, installing it on your device and saving some patients, then installing the new version to repro.

**Comment by yousefhamza** [comment]
Well, There's a lot here
I removed that initial syncing screen, that wasn't a good idea.
But mostly refactoring, and most exciting thing ever happened, I FIXED The coredate bug! :dancer: 
Anyway after I reimplemented the add patient and edit patients forms, I left the old files just in case

notice that add patient request fails I had a question for that on OpenMRSTalk, it's a REST thing.

One thing I was unable to test is migrating behaviour after that coredata fix, so If you can test that @Undo1 that would be awesome.

**Comment by Undo1** [comment]
This all sounds great, thank you! I'll try to test it tonight and get it
merged.

**Comment by Undo1** [comment]
Merged. Just a couple really small things that I fixed

 - The 'cause of death' field was only showing when the 'dead' box was *not* checked. 
 - It doesn't seem like the address field should be required - I made it not-required. If there's a reason to keep it required let me know.

Otherwise:

 - Syncing worked just fine, I tested the upgrade from the previous release and it worked fine. Awesome.
 - All the localization is great (or at least it's thorough, can't speak for the actual quality of the translations. Although running some random ones through Google Translate looks okay :P)

When do you want to release this?

**Pull request merged**
