### PR TITLE
Add Travis integration

### PR DESCRIPTION
**Pull request by yousefhamza**
I think I made it!

You need to sign in to Travis using your github then activate this repo to work with travis.

### CODE REVIEW

**Comment by Undo1** [comment]
Well, let's try it. Thanks!

**Comment by Undo1** [comment]
See https://travis-ci.org/Undo1/openmrs-contrib-ios-client/builds/62639062, it looks like everything is working except Swift compiling.

**Comment by yousefhamza** [comment]
It just worked yesterday!
https://s3.amazonaws.com/archive.travis-ci.org/jobs/62636618/log.txt

Ugh, will take a look at this..

**Comment by yousefhamza** [comment]
That will take sometime, you can turn it off for now.

**Pull request merged**
