### PR TITLE
Edit patient **online only**

### PR DESCRIPTION
**Pull request by yousefhamza**
This commits is my work for the past few days for implementing the Edit patients functionality, there was tricky parts and it can use a second eye...

Now I will be working on the offline support and syncing:
- Lightweight migration for CoreDate *adding new properties to the patient entity*
- Give an option to save when no online connection
- Check on saved patients that are NOT uptodate to save them on launch with a sync button manually at the settings.

@harshadura let me know what you think too.

### CODE REVIEW

**Comment by yousefhamza** [comment]
I will follow up with an NSLog cleaning commit after making sure everything is working

**Comment by Undo1** [comment]
Couple notes:

 - Gender should probably be a segmented control, not just a text input
 - You might want to rename "commit" to "save"
 - For the birthdate, you could use an NSDateFormatter to get a less accurate representation - we really only need month, day, and year, not time.
 - If I write something in the "preferred" field for address, then tap on another field, it crashes with this:

```
2015-06-16 11:07:44.754 OpenMRS-iOS[956:604530] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<MRSPatient 0x14e05d20> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key preferred.'
```

 - It'd be nice to have an activity indicator like we do in other parts of the app, instead of just the network indicator in the status bar.
 - If I edit John Smith (`100397` on the demo server), don't make any changes, then hit commit it crashes with:

```
2015-06-16 11:10:37.135 OpenMRS-iOS[966:605262] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<MRSPatient 0x1766a300> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key (null).'
```

Overall, though, it looks good. Just needs some polishing :)

**Comment by yousefhamza** [comment]
- That was in the back of my head then lost it
- Ok
- The dateformatter is used implicitly in MRSDateUtilities
- preferred shall be removed *Done*
- That's coming with the offline support to user to choose between Retrying or Saving it for later syncing
- What are you trying to edit? I just edited and didn't get any errors.

**Comment by harshadura** [comment]
where's the OpenMRS_iOS-Swift.h file? its missing.

**Comment by Undo1** [comment]
For the last point

 - I opened the edit view for the 100397 - John Smith
 - Didn't edit anything
 - Tapped 'commit', got the error.

I was able to reproduce this on a few others I tried. So in summary, trying to edit a patient, *but not actually change any values*, then tap commit causes a crash.

**Comment by harshadura** [comment]
Big thanks for your help in reviewing the Yosef's hard work Parker! Aren't you miss the OpenMRS_iOS-Swift.h file ? I can't build the code.

**Comment by yousefhamza** [comment]
Fixed

**Comment by Undo1** [comment]
Also, OpenMRS_iOS-Swift.h is generated at compile time, it doesn't actually exist in the file structure. Don't spend time looking for it @yousefhamza, you won't find it :)

**Comment by yousefhamza** [comment]
Offline saving/syncing added.

**Comment by yousefhamza** [comment]
@harshadura I just added above a first implementation for localization will test this more and release the localization file to the community by tomorrow.

**Comment by Undo1** [comment]
So far this looks great, I should be able to finish reviewing it sometime soon. I've been sick for the last few days. Thank you for all your work!

**Comment by yousefhamza** [comment]
Oh sorry, I hope you get well soon!
don't push it get well first.

**Comment by yousefhamza** [comment]
And that's state restoration but not full because on this branch the new patient view wasn't merged yet and that's need special handling, please try to merge as soon as possible to resolve the conflicts will happen there and continue working on that part

**Comment by Undo1** [comment]
Done, I finally started feeling better today. This is awesome, I really like the state restoration part. Thank you!

**Pull request merged**
