### PR TITLE
Initilaizing gender cell in add patient VC

### PR DESCRIPTION
**Pull request by yousefhamza**
Initilaize gender cell to male in patient
view controller.

Signed-off-by: Yousef Hamza <jo.adam.93@gmail.com>

### CODE REVIEW

**Comment by Undo1** [comment]
I'm not sure about this - are most patients male? @harshadura thoughts?

**Comment by yousefhamza** [comment]
No no no :D
That's not about males or females, this is just about initialising the selection.

**Comment by Undo1** [comment]
Right, but what advantage does having it start out with male selected over being blank?

**Comment by harshadura** [comment]
@yousefhamza , I think @Undo1 Parker's point is correct, we dont need this mod. Thanks for your effort btw.

**Pull request closed without merging**
