### PR TITLE
Patient view

### PR DESCRIPTION
**Pull request by yousefhamza**
Adding an enhanced Patient view with a TabBarController.

### CODE REVIEW

**Comment by Undo1** [comment]
Sorry for being so slow on reviewing these, I'm on vacation in the middle of nowhere. I'll try to get to it tomorrow or in SF the next day. Really appreciate your attention to detail with all of this, though!

**Comment by yousefhamza** [comment]
Don't bother, just enjoy your off time as much as u can! ;)

**Comment by harshadura** [comment]
good job Yousef!

**Comment by yousefhamza** [comment]
Can you check this out now?

**Comment by Undo1** [comment]
This is great, thank you! A couple notes:

 - The tab bar icon for visits was on the biggish side (as in huge), so I copied it and made a 30x30 version (and @2x and @3x versions) of it. See 0d7f0f9a35c669dfd70699cba834f7de3485a9b9
 - I made the title of the tab bar controller be the patient's name and ID like it was before (see 47dd5ef7858eec21f33f0778661e60f1a95ca370). I also changed the tab item title to be just the patient ID. It'd be nice to have @harshadura's opinion on what we should show here.

Overall, it's great. Thank you! Apologies for not getting to it sooner, trips and all :)

**Pull request merged**
