### PR TITLE
Some keyboards enhancements

### PR DESCRIPTION
**Pull request by yousefhamza**
Appropriate type keyboards for specific fields.

And removing the keyboard when search button is hit.

I couldn't test the capture vitals keyboard changes because the
simulator crashed on my machine when trying to search
which needs fixing and I will work on it later this week..
So it needs verification for now.

### CODE REVIEW

**Comment by Undo1** [comment]
As a workaround for the simulator crashing, you can try removing the app completely from the simulator (tap and hold on the home screen), then running it again. Sometimes the Simulator corrupts the secure database in some way.

**Comment by yousefhamza** [comment]
I reset the whole simulator removed all the apps and reset all the settings didn't work :/

**Comment by Undo1** [comment]
Finally got time to look over this. Looks great, thank you!

**Comment by Undo1** [comment]
One note @yousefhamza - make sure you set your editor to use spaces instead of tabs. This is what I use in Xcode:

screen shot 2015-03-18 at 9 49 22 pm

It's mostly a matter of taste, but it's nice to have the whole project use uniform indentation :)

**Comment by yousefhamza** [comment]
Thanks for the heads up, 

Maybe for future contributors we can write a simple "CodingStyle" File for some stuff like that and more?

**Comment by harshadura** [comment]
Nice work @yousefhamza, I just saw your contributions, Thank you for your effort on this!

**Pull request merged**
